### ISSUE TITLE
Trying to run npm start but get this Type Error.

### ISSUE THREAD

**Issue by NicholasTing** [karopolopoulos/a-song-of-monorepos-and-microservices#1]
I'm not sure what the issue is, but seems like I can't run this monorepo code.

/monorepos/a-song-of-monorepos-and-microservices/services/survey/src/index.ts:8
export const SURVEY_SCORE = Object.fromEntries(

TypeError: Object.fromEntries is not a function

node version - v12.18.3

**Comment by karopolopoulos** [comment]
Interesting, that error should only come up for Node v10.x or less.

`Object.fromEntries()` is supported from Node.js ver. 12.x .
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries

I'm using `v12.18.2` and it seemed to work ok.

Perhaps it was running node 10 in that folder? Could you replace the start command with `node --version` and see what it spits out?

**Comment by karopolopoulos** [comment]
Any luck? 😄

**Comment by NicholasTing** [comment]
Hey! Yeah thanks for that, that was precisely the issue, my nvm was using version 10 instead so I switched it to v12 and it worked perfectly.
